config/routes.rb
JargonCrusher::Application.routes.draw do
  resources :jargon_files

  resources :sources
  
  root :to => 'Sources#index'

end

app/models/jargon_file.rb
class JargonFile < ActiveRecord::Base

  attr_accessible :name, :source_id, :text_file

  belongs_to :source

  before_save :compute_jargon

  has_attached_file :text_file
  
  validates :text_file, attachment_presence: true

  def compute_jargon
    cat = "/home/web/dbacl"
    dbacl_path = "/usr/bin/dbacl -c #{cat}/jargon2 -c #{cat}/slate1 -c #{cat}/switch1 -vn"

    output = %x{ #{dbacl_path} #{text_file.queued_for_write[:original].path} }
    logger.debug "******************** #{output.inspect}"

		h = Hash.new{}
    h = parse_dbacl(output)
logger.debug "********************** #{h.inspect}"

    self.name = text_file.original_filename
    self.jargon_score = h[:jargon_score]
    self.slate_score = h[:slate_score]
    self.switch_score = h[:switch_score]
    self.composite_score = calculate_composite
  end

  def calculate_composite
		if self.switch_score == 0
			return 0
		else
			( self.jargon_score**2 + self.slate_score**2 ) / self.switch_score**2
		end
  end

	def parse_dbacl(valid_output)
		h = Hash.new 
		h[:jargon_score] = valid_output[/jargon2 +(\d+\.\d+)/, 1] 
		h[:switch_score] = valid_output[/switch1 +(\d+\.\d+)/, 1] 
		h[:slate_score] = valid_output[/slate1 +(\d+\.\d+)/, 1] 
		h[:jargonCDC_score] = valid_output[/jargonCDC +(\d+\.\d+)/, 1] 
		h[:plainCDC_score] = valid_output[/plainCDC +(\d+\.\d+)/, 1] 
		h[:letters_score] = valid_output[/letters1 +(\d+\.\d+)/, 1] 
		h
	end
    
end

app/models/source.rb
class Source < ActiveRecord::Base
  attr_accessible :name
  has_many :jargon_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jargon_files_controller.rb
class JargonFilesController < ApplicationController
  # GET /jargon_files
  # GET /jargon_files.json
  def index
    @jargon_files = JargonFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jargon_files }
    end
  end

  # GET /jargon_files/1
  # GET /jargon_files/1.json
  def show
    @jargon_file = JargonFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jargon_file }
    end
  end

  # GET /jargon_files/new
  # GET /jargon_files/new.json
  def new
    @jargon_file = JargonFile.new
    @source = Source.find(params[:source])
    @jargon_file.source_id = @source.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jargon_file }
    end
  end

  # GET /jargon_files/1/edit
  def edit
    @jargon_file = JargonFile.find(params[:id])
  end

  # POST /jargon_files
  # POST /jargon_files.json
  def create
    @jargon_file = JargonFile.new(params[:jargon_file])

    respond_to do |format|
      if @jargon_file.save
        format.html { redirect_to @jargon_file, notice: 'Jargon file was successfully created.' }
        format.json { render json: @jargon_file, status: :created, location: @jargon_file }
      else
        format.html { render action: "new" }
        format.json { render json: @jargon_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jargon_files/1
  # PUT /jargon_files/1.json
  def update
    @jargon_file = JargonFile.find(params[:id])

    respond_to do |format|
      if @jargon_file.update_attributes(params[:jargon_file])
        format.html { redirect_to @jargon_file, notice: 'Jargon file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jargon_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jargon_files/1
  # DELETE /jargon_files/1.json
  def destroy
    @jargon_file = JargonFile.find(params[:id])
    @source = @jargon_file.source
    @jargon_file.destroy

    respond_to do |format|
      format.html { redirect_to @source }
      format.json { head :no_content }
    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.json
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render json: @source, status: :created, location: @source }
      else
        format.html { render action: "new" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.json
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jargon_files_helper.rb
module JargonFilesHelper
end

app/helpers/sources_helper.rb
require 'dbacl'

module SourcesHelper
  def dbacl_output
    dbacl_command = "/usr/local/bin/dbacl -c /Users/mbsperry/myjargon/jargon2 -vnF"
    file = Rails.public_path + "/nejm"
    foobar = %x{ #{dbacl_command} #{file} }
    parsed = Dbacl.new
    parsed.output = foobar
    hash = parsed.parse_dbacl
    hash[:jargon_score]
  end
end

app/views/jargon_files/_form.html.erb
<%= form_for(@jargon_file, :html => { :multipart => true }) do |f| %>
  <% if @jargon_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jargon_file.errors.count, "error") %> prohibited this jargon_file from being saved:</h2>

      <ul>
      <% @jargon_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><b>Add File to:  </b><%= @jargon_file.source.name %></p>
    <%= f.hidden_field :source_id %>
  <p>
    <%= f.file_field :text_file %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jargon_files/edit.html.erb
<h1>Editing jargon_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @jargon_file %> |
<%= link_to 'Back', jargon_files_path %>

app/views/jargon_files/index.html.erb
<h1>Listing jargon_files</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Source</th>
    <th>Jargon score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jargon_files.each do |jargon_file| %>
  <tr>
    <td><%= jargon_file.name %></td>
    <td><%= jargon_file.source_id %></td>
    <td><%= jargon_file.jargon_score %></td>
    <td><%= link_to 'Show', jargon_file %></td>
    <td><%= link_to 'Edit', edit_jargon_file_path(jargon_file) %></td>
    <td><%= link_to 'Destroy', jargon_file, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jargon file', new_jargon_file_path %>

app/views/jargon_files/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', @source %>

app/views/jargon_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @jargon_file.name %>
</p>

<p>
  <b>Source:</b>
  <%= @jargon_file.source_id %>
</p>

<p>
  <b>Jargon score:</b>
  <%= @jargon_file.jargon_score %>
</p>
<p>
  <b>Slate score:</b>
  <%= @jargon_file.slate_score %>
</p>
<p>
  <b>Switch score:</b>
  <%= @jargon_file.switch_score %>
</p>
<p>
  <b>Composite score:</b>
  <%= @jargon_file.composite_score %>
</p>
<p>
  <pre>
    <% if @jargon_file.text_file.present? %>
      <%= render :file => @jargon_file.text_file.path %>
    <% end %>
  </pre>
</p>


<%= link_to 'Back', @jargon_file.source %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Jargon Visualization
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",    '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_graph.html.erb
<script>
  var j_points = [];
	var j_title = <% @graph_title.to_json %>
  j_points = <%= @graph_data.to_json %>;
  var plot1 = $.jqplot('chartdiv', j_points, {
    title: j_title,
    axesDefaults: {
      labelRenderer: $.jqplot.CanvasAxisLabelRenderer
    },
    axes: {
      xaxis: {
        label: "Jargon Files",
        pad: 1
      },
      yaxis: {
        label: "Jargon Score"
      }
    }
  });
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "jargon crusher", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "Sources",     '#' %></li>
          <li><%= link_to "Contact",     '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Jargon Crusher</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
	<div class="container-fluid">
		<%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/backup_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JargonCrusher</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<script language="javascript" type="text/javascript" src="/assets/jquery.min.js"></script>
<script language="javascript" type="text/javascript" src="/assets/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jqplot.canvasAxisLabelRenderer.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jqplot.canvasTextRenderer.min.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/jquery.jqplot.css" />


<div class="row-fluid">
  <div class="span2">
    <div class="well sidebar-nav">
      <table>
        <tr>
          <th align="left">Source Repository</th>
        </tr>

      <% @sources.each do |source| %>
        <tr>
          <td><%= link_to source.name, source %></td>
        </tr>
      <% end %>
      </table>

      <br />
      <hr>

      <%= link_to 'New Source', new_source_path %>
    </div>
  </div>

<% @source_data = Array.new %>
<% @sources.each do |source| %>
<% @source_data.push source.jargon_files.map { |x| x.composite_score } %>
<% end %>


<div class="span10" id='chartdiv' ></div>
<script>
  var j_points = [];
  j_points = <%= @source_data.to_json %>;
  var plot1 = $.jqplot('chartdiv', j_points, {
    title: 'Jargon Trend: All Sources',
    axesDefaults: {
      labelRenderer: $.jqplot.CanvasAxisLabelRenderer
    },
    axes: {
      xaxis: {
        label: "Jargon Files",
        pad: 1
      },
      yaxis: {
        label: "Jargon Score"
      }
    }
  });
</script>
</div>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<script language="javascript" type="text/javascript" src="/assets/jquery.min.js"></script>
<script language="javascript" type="text/javascript" src="/assets/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jqplot.canvasAxisLabelRenderer.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jqplot.canvasTextRenderer.min.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/jquery.jqplot.css" />

<p id="notice"><%= notice %></p>

<% @graph_data = [] %>
<div class="row-fluid">
  <div class="span3">
    <div class="well sidebar-nav">
      <p>
        <b>Source:</b>
        <%= @source.name %>
        <%= link_to '(edit)', edit_source_path(@source) %>
      </p>
      <table>
        <tr>
          <th align="left">File Name</th>
          <th align="left">Jargon Score</th>
        </tr>

      <% @source.jargon_files.each do |file| %>
        <tr>
          <td><%= link_to file.name, file %></td>
          <td><%= number_to_human(file.composite_score, :precision => 5) %></td>
          <% @graph_data.push file.composite_score %>
          <td><%= link_to '(del)', file, confirm: "Really Delete?", method: :delete %></td>
        </tr>
      <% end %>
      </table>
      <br />
      <hr>

      <%= link_to 'New Jargon File', new_jargon_file_path(:source => @source.id) %>
    </div>
  </div>


<div class="span9" id='chartdiv' ></div>
<script>
  var j_points = [];
  j_points = <%= @graph_data.to_json %>;
  var plot1 = $.jqplot('chartdiv', [j_points], {
    title: 'Jargon Trend',
    axesDefaults: {
      labelRenderer: $.jqplot.CanvasAxisLabelRenderer
    },
    axes: {
      xaxis: {
        label: "Jargon Files",
        pad: 1
      },
      yaxis: {
        label: "Jargon Score"
      }
    }
  });
</script>
</div>

<%= link_to 'Back', sources_path %>